services:
  postgres:
    image: postgres:18.1-alpine
    container_name: fincore-pg-db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - fincore_pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      fincore:
        aliases:
          - fineractdb

volumes:
  fincore_pgdata:

networks:
  fincore:
    external: true
